### ISSUE TITLE
The fcache hard-link count is silly, and breaks in containers where the ccache is mounted in

### ISSUE THREAD

**Issue by nicowilliams** [heimdal/heimdal#1056]
If running in a container where the `FILE` ccache is mounted from outside the container (i.e., mounting a regular file as opposed to a directory) then the hard-link count appears to be zero, which we then reject in `lib/krb5/fcache.c:584`.  I believe the hard-link count was added for some OS X related issue, but the commit that added it didn't explain in enough detail.  We should either rip that check out or make it specific to OS X.

**Comment by jaltman** [comment]
The hard link check is not OSX specific.  It was added by 2a565482f4.   The check is important because it ensures that when a file ccache is deleted that the cache will in fact be removed and not left behind for an attacker to steal the credentials from via another path.

There is an argument to be made that the check is wrong.   Instead of checking for st_nlink != 1 it should be testing for st_nlink > 1.

**Comment by nicowilliams** [comment]
But the `st_nlink != 1` check does not prevent a ccache from getting hard-linked and stolen.  Certainly we should at least change it to `st_nlink > 1`, but I think we should remove the check completely.

**Comment by nicowilliams** [comment]
The immediate issue is fixed with `58e07f88825`.
