### ISSUE TITLE
block_dns as implemented fails to block reverse DNS (PTR) lookups

### ISSUE THREAD

**Issue by riastradh** [heimdal/heimdal#1214]
**Describe the bug**
Heimdal may trigger DNS queries even though block_dns is enabled, via getnameinfo.

This is so because when drafting https://github.com/heimdal/heimdal/pull/1155 to block all paths to getaddrinfo without AI_NUMERICHOST (and now, since https://github.com/heimdal/heimdal/pull/1213, AI_NUMERICSERV), I neglected to consider reverse lookups via getnameinfo.

**To Reproduce**
- code inspection
- call krb5_sock_to_principal

**Expected behavior**
Setting `[libdefaults] block_dns = true` actually blocks all DNS queries.

Need to:
- [ ] Go through all the calls to getnameinfo and ensure they pass NI_NUMERICHOST|NI_NUMERICSERV (and maybe also NI_NUMERICSCOPE, out of paranoia).
- [ ] Update auditdns.c to provide stubs for getnameinfo and gethostbyaddr that abort except in the numeric-only cases.

**Comment by nicowilliams** [comment]
Can we not just mostly get rid of `getnameinfo()`?

 - `krb5_sock_to_principal()` is not used and should be removed (I doubt we'd be breaking any apps, but we could just leave a stub that stringifies the address and be done)
 - `ipropd-slave` uses `getnameinfo()` for debug messages, but it's pointless because we should know the upstream's name anyways (it's given on the command line and it has to be a hostname because we do call `krb5_sname_to_principal()` on it), so we don't need to look up the IP's name here ever
 - `add_locate()`'s use of `getnameinfo()` is suspect and I haven't grokked it yet, but there's no attack here
 - `debug_host()` uses `getnameinfo()`, but always with debug level 5, so we could just leave that as-is

I think that's all uses of `getnameinfo()`.  I believe we do not otherwise use `gethostbyaddr()` or `getipnodebyaddr()` (except via roken's `rk_getnameinfo()` wrapper.

**Comment by nicowilliams** [comment]
Maybe we should just have roken wrappers for reverse lookups that simply fail...

**Comment by nicowilliams** [comment]
> I have no attachment to the existing uses, except that if we keep getnameinfo in debug_host, I'd like to make it respect block_dns so you don't have to worry about cranking up debug logs causing network privacy leaks.

Agreed.

> I started to draft a change along the lines I sketched, but I can also just delete these uses instead.

If you would, I think we should at least drop the `ipropd-slave` and `krb5_sock_to_principal()` uses of it (and mark `krb5_sock_to_principal()` deprecated).  I'm going to try to understand the `add_locate()` case now.
