### ISSUE TITLE
Building with MinGW-w64

### ISSUE THREAD

**Issue by BrisingrAerowing** [heimdal/heimdal#125]
Is is possible to build Heimdal with MinGW-w64? I am trying to build a static version of cURL with kerberos support, and MIT Kerberos does not support MinGW at all. I am using MinGW because some libraries (like libmetalink and nghttp2) do not support MSVC.

I have seen that MinGW static libraries do work with MSVC, so I may try that soon.

**Comment by nicowilliams** [comment]
On Mon, Apr 20, 2015 at 10:42:18AM -0700, Brisingr Aerowing wrote:
> Is is possible to build Heimdal with MinGW-w64? I am trying to build a
> static version of cURL with kerberos support, and MIT Kerberos does
> not support MinGW at all. I am using MinGW because some libraries
> (like libmetalink and nghttp2) do not support MSVC.

It's not been done, but it should be doable.  There may be some porting
work to do around autoconf and lib/roken, but it should be possible,
yes, it just isn't currently supported (but if patches are contributed...).

Nico
--

**Comment by BrisingrAerowing** [comment]
Long time since I last looked, but I am going to fiddle with this today and/or tomorrow to see what I can come up with. I found a patch [here](https://github.com/tumagonx/pygi-mingw-patches/blob/master/heimdal-1.6.x.patch) so I am going to start with that (applying parts of it manually) and go from there. If and when I get a working build I will clean up the code I changed and create patches. It might take a while though.

**Comment by sfhacker** [comment]
Ciao. 

Maybe it is too late but we have successfully built Heimdal (server & client) with MinGW. 

Do not hesitate to contact us. 

Cheers.

**Comment by nicowilliams** [comment]
@sfhacker I would be extremely interested in support for MinGW.  Basically, right now I depend on Appveyor for Windows builds for lack of a proper Windows build system (@jaltman has Windows build systems, but I don't).  With MinGW I could ensure that I never break most basic parts of the Windows build, and I could get build artifacts I trust that I could test on Windows.

**Comment by sfhacker** [comment]
I have been contributing to this project for some time now (not at the source code level though). The first time I tried to port this project (server & client) to Windows I banged my head against the wall several times. Newer versions are less painful. I don't use Appveyor but TeamCity. I'm more than happy to provide support for MinGW (build scripts, testing (new) releases, and so on).
Are your Windows builds available somewhere? I'd love to have a look at them!

I'm not sure Secure Endpoints people use MinGW? Sometime ago I needed to use Heimdal libraries and I tried the ones provided by these guys but I faced some incompatibilities issues.

Please, email me a detailed list of 'what you have in mind' and I'll see what I can do.

Cheers.

**Comment by nicowilliams** [comment]
Secure Endpoints has its own build servers.

This project uses Appveyor to ensure that the Windows build doesn't break, but that's it.  There's no testing on Windows through Appveyor as of yet, and certainly no packaging.

A PR to add support for MinGW would mean that anyone doing a build on Linux or BSD could also make sure that the code builds on Windows.  Sure, that only means building, not testing.  But perhaps, too, we could make the existing tests run on Windows with an msys shell or with the Ubuntu shell.

**Comment by sfhacker** [comment]
Our build system makes sure all tests provided by this project are run. For this last build, we got:

# TOTAL: 112
# PASS:  102
# SKIP:  3
# FAIL:  7

We also produce an installer which takes care of setting the default values for the KDC, creates certificates and provide a console where to start the KDC server and request user tickets.
I could share with you all test results and some screenshots.
You could email me your build scripts so I can have a look at them. How does it handle Heimdal dependencies?

**Comment by nicowilliams** [comment]
@sfhacker Who are you asking?

**Comment by sfhacker** [comment]
Sorry but I'm lost now!

**Comment by nicowilliams** [comment]
@sfhacker You wrote

```
You could email me your build scripts so I can have a look at them. How does it handle Heimdal dependencies?
```

Whom did you mean should email you?  @BrisingrAerowing or @jaltman?   Oh, I guess either way... not me.

**Comment by sfhacker** [comment]
Oh I see! Sorry, I thought we (@nicowilliams & yours truly) were the only ones 'chatting' here!
I don't know either of them (@BrisingrAerowing or @jaltman). Are they in charge of the Appveyor build process?
Sorry if I confused you!

**Comment by nicowilliams** [comment]
I have nothing that isn't in the https://github.com/heimdal/heimdal git repository.  The Appveyor and Travis-CI build recipes are in-tree, as are the Windows and non-Windows build systems.

What we're talking about here is someone making a contribution to support MinGW builds from the non-Windows build system.  It would be trivial to add cross-compilation support from there, so that we could build Windows artifacts on non-Windows systems such as Linux (including Travis??), BSD, ...

(Well, I do have a script that runs `autoreconf -fi`, figures out `./configure` arguments from other arguments I give it and runs it, then runs `make -j8`, and lastly `make check`, with various steps being optional, and all in a build directory separate from the git clone.  But this isn't terribly interesting unless you frequently build in a clone.)

**Comment by sfhacker** [comment]
Far from giving you (@nicowilliams) extra work, when you have a chance, can you run the build system and email me the result (i.e. the equivalent of 'make install')? I'd like to compare it with the build system we have in place here.

Cheers.

**Comment by nicowilliams** [comment]
@sfhacker https://travis-ci.org/heimdal/heimdal

**Comment by sfhacker** [comment]
@nicowilliams Thanks for the link in the previous post. I'm not familiar with such interface and I may be asking for something that is already there. Apologies in advance. I can only see a loooonnnnnggggg log when I click on the link provided.
You know, in Linux, when you type in 'make install' you get a list of folders that include header files, libraries, executable files and so on. Is that available for download here (https://travis-ci.org/heimdal/heimdal)?
Our build script includes: make, make check and make install (on a Windows box, of course). Then we go to \bin folder, for example, and find: hxtool.exe, gsstool.exe and many other executable files. Then in \libexec folder we find kdc.exe and some other executable files.
The question I asked in my previous post (perhaps I wasn't clear enough) and I'm repeating here is: where can we download the result (or output) of 'make install'?
I'd like to compare the two build processes since we don't use Appveyor here.

Cheers.

**Comment by nicowilliams** [comment]
@sfhacker I gave you the wrong link.  The one for Appveyor is not public.  If you want Windows build artifacts I recommend you get them from [Secure Endpoints' download page](https://www.secure-endpoints.com/heimdal/#download).

**Comment by sfhacker** [comment]
Thanks for your response. I'm lost again. We have our own build process, which compiles, run tests and install this project, as I described in my previous post.
I may have misunderstood/misread your posts ('This project uses Appveyor to ensure that the Windows build doesn't break, but that's it.'). 
I'm lost. I do not know how to proceed.

**Comment by nicowilliams** [comment]
@sfhacker I'm as confused as you.  Originally you wrote:

> Maybe it is too late but we have successfully built Heimdal (server & client) with MinGW.
> 
> Do not hesitate to contact us.

So I asked for details.

We seem to have gone off the rails though.  I don't understand what you're asking of me.  Can you start from scratch?  If it's not relevant to MinGW, can you open a new issue?  Thanks.

**Comment by sfhacker** [comment]
Being able to express ourselves properly seems to be quite hard, doesn't it?

>  I don't understand what you're asking of me.
I can see that. Do you actually read the posts? If so, do you understand what you read?
I copy and paste one of my previous posts. Please try to understand it and answer accordingly:

'_You know, in Linux, when you type in 'make install' you get a list of folders that include header files, libraries, executable files and so on. Is that available for download here (https://travis-ci.org/heimdal/heimdal)?
Our build script includes: make, make check and make install (on a Windows box, of course). Then we go to \bin folder, for example, and find: hxtool.exe, gsstool.exe and many other executable files. Then in \libexec folder we find kdc.exe and some other executable files.
The question I asked in my previous post (perhaps I wasn't clear enough) and I'm repeating here is: where can we download the result (or output) of 'make install'?
I'd like to compare the two build processes since we don't use Appveyor here._'

>  If it's not relevant to MinGW, can you open a new issue?
I don't understand this. It is 100% related and relevant to MinGW! Our build scripts uses MinGW.
The title of this thread/issue goes: 'Building with MinGW-w64'. That's why I posted here.
Again, do you read what is presented to your eyes? If so, do you understand what you read?

I hope it is clear(er) now.

Cheers.

**Comment by jaltman** [comment]
@sfhacker Everything you need to build Heimdal on Windows using the Microsoft tooling is in the repository.  The instructions are in [windows/README.md](https://github.com/heimdal/heimdal/blob/master/windows/README.md).  

When `nmake /f NTMakefile` is executed it builds the SDK into  out/sdk and the binaries, msm and msi under out/dest_AMD64 or out/dest_i386 depending on the platform you are building for.

The libraries are packaged as a side by side assembly so you must have a valid code signing certificate to produce them.    The Secure Endpoints build adds proprietary components which are a part of the side by side assembly we produce.   Heimdal plugins must be distributed as part of the side by side assembly.

What @nico is offering to you is the option of adding Unix make rules for MingW to the Heimdal repository.  If that is something you would like, please submit a pull request with the necessary changes.

**Comment by sfhacker** [comment]
@jaltman Thanks for your response. I'm really lost here. Anyway, can we use nmake tools in our build scripts? We use MinGW to build Heimdal from source and so far it is working fine.
I have downloaded 'Heimdal 1.5.1 (64-bit and 32-bit)', 'Heimdal 1.6.0pre2 (64-bit and 32-bit)' and 'Heimdal 1.6.0pre2 (SDK:zip)' and installed/unzipped them. How were they built/produced? Using MinGW? Sorry about my dumb questions but I'm really confused!

**Comment by jaltman** [comment]
@sfhacker they were produced according to the directions that are in the tree to which I provided a link.

**Comment by sfhacker** [comment]
When I go to: 'C:\Program Files\Heimdal' folder, there is only one subfolder 'bin'. I could not find some of the executable files I see when using our build scripts. For instance, hxtool.exe, gsstool.exe, kdc.exe among others. Then I go to this other folder: 'Heimdal-SDK-1-6-2-0' and there are no executable files at all. Sorry about my dumb questions but I'm really confused!

**Comment by jaltman** [comment]
@sfhacker You are taking the discussion completely off-topic.   If you wish to contribute build scripts to build Heimdal with MingW, please do so.   This issue is specifically about building Heimdal with MingW.  

When you build using the Microsoft tools according to the windows/README.md instructions you will find the executables you mention in  out/dest_AMD64/bin and out/dest_i386/bin.

You are correct, Secure Endpoints does not distribute those tools.   They are not required for clients.

**Comment by sfhacker** [comment]
@neilalex We have contributed the Windows (native) port of Heimdal (both server and client) for some time now.
To the best of our knowledge, it is the only binary distribution available that includes the Kerberos server, all the client tools and all the tests. [1]

We are more than happy to assist you.

Regards.

[1] https://github.com/heimdal/heimdal/issues/325
