### ISSUE TITLE
samba VS heimdal VS mit - a fragmented concept of a protocol

### ISSUE THREAD

**Issue by dorvan** [heimdal/heimdal#244]
kerberos (heimdal and mit)
and samba (with ADDC support) 
are important service and architecture softwares to permit a lot of integrations.
but firstly kerberos it's a protocol. 
SO
but the continue problems about feature compatibility in kerberos, if solved can be a good re-start point to use it as reference protocol for new software to permit security and good integrations.
Why play to maintain it as a SLANG and not STANDARD?
Is really impossible try to fix differences and try to obtain a really good and complete protocol who can works well for all, considering it a base library of  any (*nix ) system?

**Comment by prmarino1** [comment]
This is not really a bug ticket its more of the type of thing that should be and has been discussed on the user and developer mailing lists.
That said in short here are answers some of which are current and some going back to the late 90's
Samba includes an embedded version of Heimdal and there was a divergence between the code bases, however they should have been merged as of 7.0.0, and i think even before that. you should be able to use Heimdal with Samba 4 now without issues, also Heimdal has always worked fairly well with Microsoft AD.
I've even implemented 389 server with Heimdal in AD forests without too much effort.

The primary problem here is MIT kerberos not compiling with or only partially complying with IETF RFC's.
Also there is a gap in the RFC's when it comes to the Kerberos admin protocols for complete compatibility, some new RFC's would have to be written to cover them as well.
in the LDAP db backend developers from the Heimdal project attempted to submit patches but were rejected because they claimed that they would never support Principal aliases or multiple realms in one server so they didn't want to clutter the schema with it interestingly they added principal aliasing in version 1.7 so their argument is much less convincing.

**Comment by nicowilliams** [comment]
Is there anything for us to do here?  Can you be more specific as to what you'd like?

Heimdal has some support for the MIT kadmin protocol.  Darwin has more, and we should probably adopt that.

Heimdal also supports LDAP as an HDB backend.  LDAP is the only standard interface to a KDC database.

There are also third-party tools like https://github.com/elric1/krb5_admin/.

**Comment by dorvan** [comment]
a good thing, can be discuss with different projects that implementa kerberos to find a way to follow to be really aligned, because, most use implementations ho refer to microsoft AD, for example, cause to users, developers and maintainers (of linux and unix distro pkg repos) of a large amout of work and frustration, it's not "normal" in 2017, need to split up kerberos implementations to libs, to "get it working" with other software deps, because there isn't a standard reference based on actual versions and compatibility. This is a message related to an ISSUE, not a BUG. ISSUE can be Abstracted and impact on workflow and bugs not only in your kerberos implementation.  It's like the situation of cyrus mail server, excellent software, really, but have a documentation only to clusterize it. if you have to setup a base mail server, you don't have the basic documentation and a list of steps or an explanation of fundaments to configure it. It's not a bug it's an ISSUE! for example SAMBA... looking to major distro packaging and binary pkg development, maintainers goin'crazy to split up kerberos bindings, in small pieces related on role of samba you want because more deep implementations (AD DC) want heimdal (a really software chapeu!) but if you want to use samba (applicative package) ad AD DC, or if you plan "to be interested in future to use it" making a default installation, to switch from mit krb system kerberos installation, to heimdal.... this it's not a problem... a part all other core libs or well known application packages and features who wants mit krb as system lib. ldap, sssd daemon... a lot of application that have bindings with ldap, kerberos or radius.  

as user, and as devop, i please here heimdal team to find a way, discussing with other kerberos projects and developers to find a way, to solve this ISSUE.

I know can be sound like an utopia, but it's a first step.
since 2002 i've lost hour and hour on systems for kerberos conflicts.

but i like your work, and appreciate the evolution of differente kerberos project, but probably now it's time to reduce fragmentation.

**Comment by abartlet** [comment]
This isn't a bug, more a philisophical point on having different implementations for the same protocol, normally considered a good thing but difficult when the libraries are so close in function and can mostly replace each other. 

Samba is trying to also support MIT krb5 as a KDC, but it is not finished yet:

https://wiki.samba.org/index.php/Running_a_Samba_AD_DC_with_MIT_Kerberos_KDC
