### ISSUE TITLE
Don't ignore entries in /etc/hosts

### ISSUE THREAD

**Issue by frozencemetery** [heimdal/heimdal#32]
It would be nice if entries in /etc/hosts were treated as they are in MIT (i.e., not ignored).  This would allow for the same krb5.conf to be shared between the two instead of having to hardcode the IP address of the kdc in krb5.conf for Heimdal.

**Comment by nicowilliams** [comment]
The trailing dot is useful to defeat "searching" a domain search list, which is desirable for security reasons (i.e., so that one cannot be forced to walk down the search list by spoofing `NXDOMAIN` (or, in the cases of particularly buggy resolvers, `SERVFAIL`) responses.

The obvious compromise is to try it first one way, then the other, and accept only results that list the query name as a hostname or alias in the result.
