### ISSUE TITLE
Error 29 KRB5KDC_ERR_SVC_UNAVAILABLE causes infinite looping in krb5_sendto_context()

### ISSUE THREAD

**Issue by ScottUrban** [heimdal/heimdal#346]
Calling krb5_init_creds_get() or other function that sets _krb5_kdc_retry on the ctx.

Here's the apparent flow:

krb5_sendto_context()
 - case KRB5_SENDTO_CONTINUE
 -- wait_response
 --- receives reply into ctx->response
 --- sets *action to KRB5_SENDTO_FILTER
 REPEAT
 - loop around, case KRB5_SENDTO_FILTER
 -- _krb5_kdc_retry()
 --- decodes, error->error_code = 29
 --- 29 mapped to ret KRB5KDC_ERR_SVC_UNAVAILABLE
 --- *action set to KRB5_SENDTO_CONTINUE
 - loop around, case KRB5_SENDTO_CONTINUE
 -- wait_response()
 --- sees we already have a response
 --- *action set to KRB5_SENDTO_FILTER
 --- repeat

Once this starts happening, ctx->response isn't changed. Not sure why we got error 29 to start with.  Googling, either not a real error, or maybe a certificate problem. We saw this when our server was getting going through a restart, not sure if that is relevant. Process termination was blocked on this spinning thread until the service manager did a hard kill.

We're running 7.4 with a few unrelated local patches.

Thanks
Scott

**Comment by nicowilliams** [comment]
Error 29 is `KDC_ERR_SVC_UNAVAILABLE`, per [RFC4120](https://tools.ietf.org/html/rfc4120), see [page 112](https://tools.ietf.org/html/rfc4120#page-112):

```
   KDC_ERR_SVC_UNAVAILABLE               29  A service is not available
```

Normally this means "keep trying".  So the issue, really, is that we need a max number of retries.  And, of course, the KDC shouldn't be returning `KDC_ERR_SVC_UNAVAILABLE` for non-transient errors.

What KDC is this and why was it returing `KDC_ERR_SVC_UNAVAILABLE`?  How many KDCs do you have?  Did this loop forever, or only until you ran out of patience?

I'm labeling this a bug for now because I don't see how to set a max retries for this...

**Comment by ScottUrban** [comment]
The loop doesn't retry anything - it spins as described consuming 100% cpu on a core without making any more requests to the KDC. Eventually, the process was given a kill -9 by the service manager. Maybe I'm missing something. 

I don't know the KDC; this was at a customer's site. I can try to find out if it is important.

**Comment by nicowilliams** [comment]
Oh!  OK, thanks for the report!

**Comment by nicowilliams** [comment]
As to the KDC, I was wondering if there was a second bug in Heimdal related to this.  That's all.

**Comment by ScottUrban** [comment]
Ok, I'm inquiring through channels to get more info about customers kdc setup.

Regarding the bug, it seems like in _krb5_kdc_retry(), if you see unavailable, the code could set *action to KRB5_SENDTO_RESET to get out of the spin and perhaps do the right thing new requests until retry count is exhausted.

Thanks

**Comment by nicowilliams** [comment]
I agree.  It seems that all `_krb5_kdc_retry()` should be doing is handling the `KRB5KRB_ERR_RESPONSE_TOO_BIG` case, either leaving `action` alone (`KRB5_SENDTO_DONE`) or setting it to `KRB5_SENDTO_RESET`, but never setting `action` to `KRB5_SENDTO_CONTINUE` (since we'll not have resent a request, there's no point waiting for a response).

**Comment by nicowilliams** [comment]
I believe the correct next state when the KDC returns `KDC_ERR_SVC_UNAVAILABLE` is `KRB5_SENDTO_TIMEOUT`, at least for now, but it would either be better to move to the next KDC immediately, or sleep a bit.  I don't see where this code ever sleeps... which is strange.  Ah, I get it.  On timeout we always go to the next KDC, which is why we don't need to sleep: we wait in `select()`, and we round-robin KDCs.  Still, if all KDCs fail with `KDC_ERR_SVC_UNAVAILABLE` we ought to sleep a bit before retrying once we run out of KDCs.

**Comment by nicowilliams** [comment]
Actually, no, that's wrong, at line 284 we need to clear the response and continue.

**Comment by ScottUrban** [comment]
Regarding environment, I heard back from our customer. No separate KDC. Single domain controller. "Windows Server 2008 R2 SP1 updated with all patches".

**Comment by LewisR** [comment]
PMFJI...

As someone who recently finished a project on OS/2 authenticating against Windows, I can say that I have seen this when the server has been restarting (i.e., unavailable). A single Windows PDC is the KDC, so that's to be expected. If there are no other KDCs available, we should just give up, as Nico suggested in his edit.

So, is the issue here that we're not giving up or that the error 29 was unexpected in the first place? To my thinking, the 29 is entirely expected if the only KDC (PDC, in this case) is unavailable. The bug to be considered is why we didn't just give up after that when there were no more KDCs to try. Is there anything interesting in the krb5.conf? Maybe there's some junk in there which is confusing us.

Again, apologies for just butting into this thread, but I have experienced something similar. I'll need to look at the code to see how we worked around it, though.

**Comment by ScottUrban** [comment]
@LewisR the issue is the code spins without retrying the single DC and without return an error to the caller.  

Unless I hear otherwise, I'm going to try a fix informed by the discussion in this thread.

Unfortunately, I don't know of a way to make a DC return this an error. My repro involves a unittest and injecting the error in the reply packet with a debugger.  If anyone has advice on error injection with a real DC or on applicable heimdal tests, I'd like to hear it.

Thx

**Comment by abartlet** [comment]
I've seen this in a broken Samba (during development) and the easiest way to reproduce it will probably be to hack Samba's KDC to just always return it.  I plan to do that to validate a proposed patch for this.

**Comment by ScottUrban** [comment]
We've been running with this patch for about 10 months:
`diff -u a/lib/krb5/send_to_kdc.c b/lib/krb5/send_to_kdc.c
--- a/lib/krb5/send_to_kdc.c
+++ b/lib/krb5/send_to_kdc.c
@@ -275,7 +275,7 @@
        break;
     }
     case KRB5KDC_ERR_SVC_UNAVAILABLE:
-       *action = KRB5_SENDTO_CONTINUE;
+       *action = KRB5_SENDTO_RESET;
        break;
     }
     return 0;`
