### ISSUE TITLE
Restoring ftp and telnet clients (or servers too?)

### ISSUE THREAD

**Issue by mmokrejs** [heimdal/heimdal#358]
Hi,
  every once in a while I need some simple ftp client to transfer a few files or to telnet to port 80, 53, etc. I always go for kftp and ktelnet but they are just gone from heimdal these days. What was the reason to drop them? 

https://github.com/heimdal/heimdal/blob/49d56916e169ee9a1cb31e21ac7349b985bcc8eb/NEWS#L106-L107

Do I really need to get the clients from other packages? This is not about whether plain or kerberized ftp is secure or not (maybe you even supported some TLS on top, not sure), we still need it time to time.
  Would you please reconsider your past decision? Thank you,

**Comment by jaltman** [comment]
The legacy applications were removed from Heimdal because they were unmaintained, suffered from poor coding practices, and were unused by most downstream distributions.   The ftp, telnet, rcp, and rsh protocols themselves are insecure and have been deprecated.

**Comment by habazut** [comment]
Just discovered the hard way this "feature" (it's labled like this in NEWS) since version 7.1.

I have to say that ftp/ftpd is still used here and that xnlock is the only screen lock I found so far which works. For example the screen lock that comes with gnome was defeated by my 3-year old (input from keyboard until crash). So I'd be sad to loose these when I upgrade.

This would be my summary:

ftp/ftpd: Still used
telnetd: Unsecure, not used
telnet: Can be replaced by any other telnet (as the kerberos features are not used any more)
rcp/rsh/rshd: Unsecure, not used
kx/kxd: Not usesd here, but why discontinue a small and maybe for someone useful program.
push/pop: I know places where that is still in use
xnlock: Used by me (you're welcome to suggest a working replacement)

Harald.

**Comment by jaltman** [comment]
The source code is available in the repository and in prior releases.  You and those that are willing to provide the resources to develop and support the applications you wish to maintain are free to do so as a standalone product distribution.

In case you were unaware, MIT's Kerberos removed extraneous and poorly supported applications from their Kerberos distribution in 2009.  

The active developers of Heimdal do not have the resources to maintain the applications.  

Applications that have not been modified in years can and should be maintained outside the Heimdal distribution.

**Comment by kaduk** [comment]
(The MIT analogues were "maintained" in a separate repo for several years, though they received little attention there.  They were officially desupported just in the past year or two.)

**Comment by jaltman** [comment]
The plan for the separate repo, available at https://github.com/krb5/krb5-appl, was that someone other than the MIT Kerberos team could fork it and take over responsibility for it.   It is worth noting that no one other than MIT Kerberos team members contributed to the support of the repository since its inception in 2009. 

None of the improvements that were made to the SRP fork of the MIT applications in particular support for START_TLS ever made it back into the MIT code base.   START_TLS made use of anonymous-DH and Kerberos AUTH channel bindings to provide a security channel.  

The SRP application fork also compiled against both MIT and Heimdal.  I would advise anyone that is interested in maintaining Kerberized applications to fork the MIT repository and then create an application distribution that builds against both MIT and Heimdal Kerberos.

**Comment by habazut** [comment]
Well, you have a point and ftpd would need modifications to handle mixed IPv4/v6 sockets correctly. Maybe I could tryu to revive xnlock as a soft starter. Miss the guy with the big nose ;-)
