### ISSUE TITLE
Inaccessble ~/.k5login breaks sshd gssapi-with-mic

### ISSUE THREAD

**Issue by feld** [heimdal/heimdal#368]
Hello,

Heimdal in FreeBSD 11.1 base and older versions exhibit this bug. If you lock down user directory permissions to 0700 and try to use gssapi-with-mic it will fail to work.

```
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-with-mic,keyboard-interactive
debug3: start over, passed a different list publickey,gssapi-with-mic,keyboard-interactive
debug3: preferred gssapi-with-mic,publickey,password,keyboard-interactive
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,password,keyboard-interactive
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug3: send packet: type 50
debug2: we sent a gssapi-with-mic packet, wait for reply
debug3: receive packet: type 60
debug1: Delegating credentials
debug3: send packet: type 61
debug3: receive packet: type 61
debug1: Delegating credentials
debug3: send packet: type 66
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-with-mic,keyboard-interactive
debug1:  An invalid name was supplied
unknown mech-code 0 for mech 1 2 752 43 14 2

debug1:  Miscellaneous failure (see text)
unknown mech-code 0 for mech 1 3 6 1 5 5 14

debug1:  Miscellaneous failure (see text)
unknown mech-code 2 for mech 1 3 6 1 4 1 311 2 2 10

debug1:  An unsupported mechanism was requested
unknown mech-code 0 for mech 1 3 5 1 5 2 7

debug1:  Miscellaneous failure (see text)
unknown mech-code 0 for mech 1 3 6 1 5 2 5

debug2: we did not send a packet, disable method
```

I presume there's some faulty logic in krb5_kuserok(3) that doesn't handle the read failure properly. It would be great if this functionality could also be disabled by default and configurable in kr5b.conf as this functionality violates security policies of most modern orgs.

**Comment by kaduk** [comment]
One could argue that this is in fact a feature (failing safe), since .k5login can be used to restrict access that would otherwise be granted if it is absent.

**Comment by feld** [comment]
Wouldn't the sane approach be to lock the user account to restrict access? If Heimdal is incompatible with secure permission enforcement on user home directories I think a larger conversation should be had here.

As for the code, I believe I have located the specific issue:

https://github.com/heimdal/heimdal/blob/master/lib/krb5/kuserok.c#L661-L677

The result is likely TRUE when a permissions error is encountered because permission errors are not  taken into consideration and then we hit the "An invalid name was supplied" because it couldn't get anything out of the ~/.k5login file.

**Comment by jaltman** [comment]
@feld, is there a reason the system administrator wouldn't specify configuration in the system's /etc/krb5.conf file to disable use of ~/.k5login files or specify an alternative userok plugin than the ~/.k5login plugin?

As @kaduk indicated, ~/.k5login can restrict access as well as grant it.   Failure to read the file because of EACCES or EPERM could result in access being granted that shouldn't be.   Therefore, I believe the ~/.k5login plugin is behaving correctly when the plugin is specified as being authoritative.

**Comment by feld** [comment]
What option in krb5.conf permits the ability to disable use of ~/.k5login files? Was this feature added in the silent years that went by with no software releases? It's not in version Heimdal 1.5.2 or at least not documented from what I can tell. I have been searching for this for months.

**Comment by kaduk** [comment]
It looks like there's a lot of potential options, maybe

```
[realms]
        <DEFAULTREALM> = {
                 ...
                  auth_to_local = NONE
         }
```

or

```
[libdefaults]
        kuserok = SYSTEM-K5LOGIN
```

and then put any needed configuration into (root-owned, world-readable) ```/etc/k5login.d``` and possibly more that I'm missing due to lack of familiarity.

**Comment by feld** [comment]
Neither of those options exist in Heimdal 1.5.2 in FreeBSD 11.1-RELEASE. Is FreeBSD the largest deployment of Heimdal Kerberos out there? It seems to be as Linux seems to only deploy MIT.

How can we get these options backported into the Heimdal in FreeBSD for the 11.2-RELEASE? I really need solutions for the near term and at this point it appears FreeBSD is on the verge of replacing Heimdal for MIT in a future release, so if this is going to require me to wait for 12.0-RELEASE for any hope of this being an option by then I'll have likely be using MIT anyway.

**Comment by feld** [comment]
Additionally, is there any documentation for Kerberos (Heimdal or MIT or whatever) anywhere on the internet or in print that suggests "changing the mode of ~/.k5login" as a reliable, viable, and serious approach to limiting an account's access to a server?

This appears to be unwritten lore and it's hard to accept as a serious approach considering this is a file that the user owns and they could revert via an existing logged in session (especially if it's on an NFS home). Not even comments in the code itself mention this as expected behavior.

**Comment by jaltman** [comment]
We don't control nor influence what operating system distributions ship.   Heimdal for Red Hat Linux platforms is packaged as part of EPEL.   Debian and Ubuntu each package Heimdal for themselves.  I'm not sure about other Linux distributions.    In any case, whether it be Linux, BSD, Solaris, macos, iOS, etc, the operating system vendors make their own choices about what to ship or backport.  

You should be filing bug or feature requests with the source from which you obtain Heimdal.  

As for changing the mode of ~/.k5login as a means of blocking access, that is not a feature.   What is a feature is that the contents of a ~/.k5login file can restrict access or grant access.  When Heimdal is configured to use ~/.k5login files and the file exists but is not readable, it is impossible for the library to know whether the ~/.k5login file would grant access or refuse it.  Therefore, a failure to read the file contents must be treated as a refusal.  To do otherwise would create a security vulnerability.

**Comment by kaduk** [comment]
As a very concrete example of k5login restricting access, consider the case such as at MIT where the principal ```root@ATHENA.MIT.EDU``` exists in the KDB.  While I assume that this principal is either locked or controlled by an administrator in some fashion, it's also the case that I don't want a compromise of it to give root access to my machines.  So, I have a ```/root/.k5login``` file that (usually) contains ```kaduk/root@ATHENA.MIT.EDU```, which is the principal that I actually want to be able to log in as root.  If, for whatever reason (accidental or otherwise), ```/root/.k5login``` becomes unreadable, then I do *not* want the default behavior of allowing ```root@ATHENA.MIT.EDU``` to log in -- denying access is a better fit for my security model, even if it means that I may need to access the console in order to recover the system.

**Comment by dlangille** [comment]
I  believe this is best fixed by a knob which says: ignore ~/.k5login

We got around it by creating a custom library.  At present, it's still an issue.
