### ISSUE TITLE
Make `gss_release_oid()` do nothing

### ISSUE THREAD

**Issue by jaltman** [heimdal/heimdal#447]
_Originally posted by @nicowilliams in https://github.com/heimdal/heimdal/pull/433#issuecomment-447441369_

**Comment by jaltman** [comment]
Make `gss_release_oid()` do nothing -- it should never have existed.  `gss_str_to_oid()` should intern and its outputs never freed (except at library unload time, and arguably we should not support library unload).

**Comment by nicowilliams** [comment]
We don't even have a `gss_str_to_oid()`, which means this is an even simpler fix.

**Comment by lhoward** [comment]
So it should look like this?

```
GSSAPI_LIB_FUNCTION OM_uint32 GSSAPI_LIB_CALL
gss_release_oid(OM_uint32 *minor_status, gss_OID *oid)
{
    if (minor_status != NULL)
        *minor_status = 0;

    *oid = GSS_C_NO_OID;

    return GSS_S_COMPLETE;
}
```

**Comment by jaltman** [comment]
yes, if Heimdal only ever returns static objects, but I believe if we return allocated objects we should store them somewhere and always return the same object.

**Comment by lhoward** [comment]
Yes, interning would be better, unless we can safely make gss_duplicate_oid() a NOOP (but that's dangerous if we cannot assert the input is a static object). (The only uses of gss_duplicate_oid() inside Heimdal are in SPNEGO, but it is a public API.)

We may also need to consider how to deal with pluggable mechanisms. In MIT Kerberos, mechanisms can implement gss_internal_release_oid() which will return GSS_S_COMPLETE if they recognised the OID (i.e. it was one they statically allocated or otherwise interned).

Need to think about this for a bit.

**Comment by lhoward** [comment]
Heimdal and MIT have fairly different behavior here. The simplest options I can think of are to do nothing (as in, leave Heimdal as-is), or to match the MIT behaviour. A more complicated option might be to intern OIDs that cross the API boundary but I'm not exactly sure if that buys us anything.

**gss_duplicate_oid**

Heimdal returns an allocated deep copy; MIT does not have this API.

**gss_add_oid_set_member**

MIT does a deep copy, Heimdal a shallow one. This is not an issue when dealing with statically allocated or interned OIDs (as the behavior is matched by `gss_release_oid_set()`) but it is when dynamically allocating them.

For example, mech_eap will release dynamically allocated OIDs after calling `gss_add_oid_set_member()` when building with MIT, but not with Heimdal. If we change the implementation and wish to retain binary compatibility with deployed mechanisms, then we will need to be OK with leaking memory until the mechanisms can themselves be updated. (And, when the mechanisms are updated, we need to be careful they are not loaded by an earlier version of Heimdal, to avoid a double free. This may be hard to prevent in practice.)

**gss_release_oid**

Heimdal always frees the OID contents; MIT gives each mechanism an opportunity to mark the OID as freed (so they can avoid freeing interned OIDs); the OID is freed iff no mechanism marks the OID as freed and the OID is not a mechglue OID.

**gss_release_oid_set**

Heimdal only frees the containing array; MIT frees the OIDs themselves as well (bypassing `gss_release_oid()`). This matches with `gss_add_oid_set_member()`.

**Comment by lhoward** [comment]
Actually, I realise the mechanisms I've written already leak with Heimdal when using `gss_add_oid_set_member()`. So – I propose we match the MIT behaviour including the `gss_release_oid_internal()` SPI (which I believe came from the Sun code).

@nicowilliams @jaltman let me know if you are OK with this approach. IIRC Heimdal's OID are in a single array so it's straightforward to test whether Heimdal's OIDs are interned or not.

**Comment by nicowilliams** [comment]
Regarding `gss_add_oid_set_member()`, I'd say let it not copy the OID, but use the pointer from the input OID.  Then `gss_release_oid_set()` need not release OIDs.

As to `gss_release_oid()` and `gss_duplicate_oid()`, and even `gss_str_to_oid()` (which Heimdal doesn't have), I'd rather that we intern OIDs in a trivial, global static, singly-linked list that we thread-safely push on with a CAS intrinsic and which we search linearly.  If you duplicate an OID, you'll pay a price (`gss_accept_sec_context()` does duplicate OIDs, but that's just dumb since it has a table to take an OID from that it knows won't be freed; ditto SPNEGO.  That's all uses in Heimdal.  And then `gss_release_oid()` should do nothing.

**Comment by lhoward** [comment]
On the first point: that's what Heimdal does today. Which is fine, except it means you can't add an allocated OID unless you intern it first. (Maybe that is fine and that mech_eap does not do that today is a bug: fair enough.)

IIRC portable CAS intrinsics aren't exposed outside of heimbase. But we could do that (or put the list logic into heimbase).

**Comment by nicowilliams** [comment]
If we remove `gss_duplicate_oid()`, or just let it leak, then we can have `gss_release_oid()` do nothing.  I'm partial to this.

**Comment by lhoward** [comment]
I'm implementing the interning using HEIM_SLIST, then I need to make SLIST thread-safe.

**Comment by lhoward** [comment]
Just FYI for anyone that reads this in the future, notes above about deep vs shallow copies were wrong. It’s always a deep copy as an OID set is an array of structures, not pointers.
