### ISSUE TITLE
Implement gss_set_neg_mechs()

### ISSUE THREAD

**Issue by lhoward** [heimdal/heimdal#495]
```c
OM_uint32 
gss_set_neg_mechs(OM_uint32 *minor_status,
                  gss_cred_id_t cred_handle,
                  const gss_OID_set mech_set);
```

NB – Nico has a good idea about how to do this, given SPNEGO returns mechglue creds, we could have a helper function e.g. `__gss_drop_cred_by_mech()` that operates on the MG cred.

**Comment by nicowilliams** [comment]
Yes, this should be a mech method.

The SPNEGO mech can implement this in a number of ways, but since it currently doesn't wrap `gss_cred_id_t` values in a SPNEGO wrapper, and to keep the amount of change down, there are two ways to implement `gss_set_neg_mechs()` without adding such a wrapper:

1. Throw away the current `gss_cred_id_t` and replace it with one acquired with `gss_acquire_cred()` with the `desired_mechs` set to the same OID set as in the `gss_set_neg_mechs()` call.  This violates the POLA.
2. Add a `gss_drop_cred()` function that drops an element of some `desired_mech` in the given `input_cred_handle`.  Unlike `gss_add_cred()`, now that we have `gss_duplicate_cred()`, we don't have to conflate mutation and duplication in one function, so `gss_drop_cred()` doesn't need an `output_cred_handle` parameter.

(1) breaks if either the credentials can no longer be re-acquired, or if they were acquired with `gss_acquire_cred_from()`/`gss_add_cred_from()`.  If we can do (2), that would be better.

**Comment by greghudson** [comment]
Is it important to release the no-longer-negotiable mech creds from the SPNEGO cred, or is it sufficient to just remember which mechs are negotiable?

**Comment by nicowilliams** [comment]
@greghudson Good point, but I assume real-world apps call `gss_set_neg_mechs()` just once per-cred.

**Comment by lhoward** [comment]
BTW if I read the Apple Heimdal code correctly, their SPNEGO mechanism expects unwrapped mechglue creds (they have a flag to poke a hole, `GM_USE_MG_CRED`), i.e. creds for the actual mechs you want. This breaks tests that acquire only a single SPNEGO cred. But it avoids layers and layers of creds. The existing Heimdal code checks `GM_USE_MG_CRED` in a couple of places but does not set it in SPNEGO.

**Comment by lhoward** [comment]
I wrote a very untested implementation!

**Comment by lhoward** [comment]
Merged
