### ISSUE TITLE
hl5.org down?

### ISSUE THREAD

**Issue by dothebart** [heimdal/heimdal#621]
Hi, 
all requests to https://www.h5l.org/ run into a timeout?

**Comment by dpieski** [comment]
still happening

**Comment by walmav** [comment]
Appreciate if someone could point me at an alternative way of reading the docs. Perhaps there a docs Github repo

**Comment by quanah** [comment]
Just to note, this is being looked at.

**Comment by MisterSpicy** [comment]
The mailing list sites are also down: heimdal-announce and heimdal-discuss.

**Comment by ajorajev** [comment]
> Just to note, this is being looked at.

do you know, when website comes back? any guesstimates?

**Comment by jaltman** [comment]
It is unlikely that www.h5l.org will be restored.    The h5l.org domain is controlled by someone that is no longer active in the project and at the present time that individual is unable to transfer control due to technical issues.   The domain heimdal.software has been registered for use by this project and https://heimdal.software/ refers to https://gitbub.com/heimdal/.

**Comment by dothebart** [comment]
Hi, thanks for the update; 
Hopefully google will pick up this quickly.

**Comment by steakknife** [comment]
https://web.archive.org/web/20190806100337/http://www.h5l.org

Maybe copy the content from archive dot org with a wget mirror script and strip out all of the injected archive toolbar cruft in web pages.

**Comment by jaltman** [comment]
@steakknife Thank you for the suggestion but no content has been lost.  The web site content is generated from https://github.com/heimdal/h5lweb/.

**Comment by jaltman** [comment]
The h5l.org domain now forwards to https://github.com/heimdal/
