### ISSUE TITLE
Shouldn't kadmind timeout stale clients?

### ISSUE THREAD

**Issue by theseal** [heimdal/heimdal#745]
**Describe the bug**
We run kadmind with inetd on Debian Stretch.

We have a few "bad" kadmin clients written in Perl with [Heimdal::Kadm5](https://metacpan.org/pod/Heimdal::Kadm5). They where written in a way that makes them not close the connection in a good way and probably timeout more then often and then spawn a new connection when needed. The client itself doesn't think it has an ESTABLISHED connection to kadmind but the kadmind thinks otherwise. This is usually not a problem but this morning I found inetd stuck trying to fork yet another kadmind to due of ulimit was fulfilled with stale (very very old) processes.

Guess that that is two parts of the problem. I will look in to the first part and see if I can handle my clients in a better way but shouldn't `kadmind` have some kind of timeout to prevent this behaviour?

**Expected behavior**
kadmind to timeout stale connections

**Comment by theseal** [comment]
Can be reproduced with this snippet
```
#!/usr/bin/env perl

use warnings;
use strict;

use Heimdal::Kadm5 qw();

my $principalname = "host/host.example.com";
my $krbtime    = time;
my $krbtimeout = 4 * 60 * 60;
my $krbclient  = get_krbclient();

sub get_krbclient
{
    $krbtime = time + $krbtimeout;
    return
      Heimdal::Kadm5::Client->new(
                               Principal => 'kadmin',
                               Realm     => 'EXAMPLE.COM',
                               Keytab => 'kadmin.keytab'
      );
}

while (1)
{
    if ($krbtime < time + ($krbtimeout / 2))
    {
        $krbclient = get_krbclient();
    }
    my $principal = $krbclient->getPrincipal($principalname);
    sleep 36000;
}
```

**Comment by jaltman** [comment]
The addition of socket level keepalives is necessary because it prevents a TCP connection from living indefinitely even if the client has died without terminating the connection.   However, it isn't going to address this report.   That is because the bug in your client, or at least in the provided reproduction, is to create new kadmin sessions, keep the connections open and never terminate them.   That is a bug in the client; it is not necessarily a bug in the kadmin service.   Establishing a long lived connection that receives periodic requests separated by long idle periods is something that many sites rely upon.   If the client dies, then the TCP connection should eventually fail, but that requires the keepalive option to be enabled. 

There isn't a timeout option for the protocol.   I am going to change this to a feature request.

**Comment by theseal** [comment]
I think I fixed my clients.

Adding a timeout option would be a great addition since not all connections from the real `kadmin` is terminated in a correct way.

**Comment by jaltman** [comment]
> Adding a timeout option would be a great addition since not all connections from the real `kadmin` is terminated in a correct way.

As long as the socket is closed the tcp keep alive will result in kadmind terminating. The timeout is only required if the client process never closes the socket, and the either never terminated or the socket is inherited by child processes.
