### ISSUE TITLE
kerberos(8) man page url is no longer accessible

### ISSUE THREAD

**Issue by yzgyyang** [heimdal/heimdal#766]
**Describe the bug**
In https://github.com/heimdal/heimdal/blob/master/lib/krb5/kerberos.8#L76, the URL listed is no longer available.

**Comment by kenh** [comment]
Well, SINCE you asked ...

The Kerberos FAQ hasn't been updated in a long long time.  It would take a lot of time for me to do that, and .... well, I'm not a young man anymore, and I've got a kid, a mortgage, I'm trying to exercise more, and generally keep my head above water in the middle of a global pandemic and a possible violent overthrow of the United States Government.

I don't mean to dump all of my existential issues in a github issue comment of all places, even though I guess that is what I am doing right now. I suppose this is a long way of saying, "Go ahead and delete that link, I don't think the Kerberos FAQ is coming back".

**Comment by kaduk** [comment]
Thanks, Ken.  I appreciate that you took the time to respond; while it may not make me happy to propose removing the link, it is seeming like the right thing to do at this point.
