### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by 0-wiz-0** [heimdal/heimdal#849]
heimdal is noted as affected by CVE-2021-3671.
This is fixed by https://github.com/heimdal/heimdal/commit/04171147948d0a3636bc6374181926f0fb2ec83a but the diff does not apply to the 7.7.0 release
```
ld: ./.libs/libkdc.so: undefined reference to `_kdc_set_e_text'
```
Can you please make a new release?

**Comment by brianmay** [comment]
Last time Debian switched to the git version of Heimdal to get needed fixes, it upset people because we ended up making stable Debian releases from what was considered an unstable version of Heimdal. Fair enough.

So what should Debian do regarding CVE-2021-3671? Do we leave it unpatched? Or do we switch to the git release from the 7-1 branch?

What about old releases of Debian which have security support that cannot make major changes to upstream code?

**Comment by brianmay** [comment]
@quanah Is there anywhere I can access your back ported changes?

Thanks in advance :-)

**Comment by abartlet** [comment]
On Tue, 2021-11-16 at 15:49 -0800, Brian May wrote:
> @quanah Is there anywhere I can access your back ported changes?
> 
> Thanks in advance :-)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or
> Android. 

This all started with Samba, and here is what we did for our old
version:

https://gitlab.com/samba-team/samba/-/commit/0cb4b939f192376bf5e33637863a91a20f74c5a5

-- 
Andrew Bartlett (he/him)       https://samba.org/~abartlet/
Samba Team Member (since 2001) https://samba.org
Samba Team Lead, Catalyst IT   https://catalyst.net.nz/services/samba

Samba Development and Support, Catalyst IT - Expert Open Source
Solutions

**Comment by brianmay** [comment]
@abartlet Will try that, thanks.

**Comment by jaltman** [comment]
@nicowilliams and I are working on a new release but it is not ready yet.

**Comment by jaltman** [comment]
> Last time Debian switched to the git version of Heimdal to get needed fixes, it upset people because we ended up making stable Debian releases from what was considered an unstable version of Heimdal. Fair enough.

I get upset when downstream distributions decide to ship random sha1's from the 'master' branch of upstream projects because that branch is likely to be unstable and potentially includes more flaws than fixes.
 
> So what should Debian do regarding CVE-2021-3671? Do we leave it unpatched? Or do we switch to the git release from the 7-1 branch?

The 7-1-branch is the stable branch.   The tip contains stable back-ported fixes and/or minor features that are intended for near term production use.   I would not object to pulling changes from the tip of 7-1-branch for a downstream patch release of 7.7.  The next version in the 7.x series will be 7.8.  
  
> What about old releases of Debian which have security support that cannot make major changes to upstream code?

How old?

**Comment by brianmay** [comment]
See https://packages.debian.org/search?searchon=sourcenames&keywords=heimdal - there is a 7.1, 7.5 and a 7.7 we have to maintain.

@abartlet patch worked for 7.7, my guess is it might work for 7.1 and 7.5 too, but haven't tried it yet.

**Comment by abartlet** [comment]
Not that it is your problem, but Samba will be in this pickle soon, I
need to take a snapshot of master in the next month or so, ideally
after the Apple FAST patches land (we are doing some testing of those).
 Our last 'snapshot' lasted about 10 years, but we hope to sync up more
regularly this time...

**Comment by nicowilliams** [comment]
We're working on a new release.

**Comment by brianmay** [comment]
I believe this is being discussed here: https://kb.cert.org/vince/comm/case/162/

Having said that, I can't access the case from my account and nobody is responding to my requests either.

**Comment by jaltman** [comment]
I have no access to that URL

**Comment by nicowilliams** [comment]
We're waiting on #950 for a Heimdal 8.0 release, which just needs more Windows testing.

**Comment by nicowilliams** [comment]
Ah, I think I found it anyways.

**Comment by brianmay** [comment]
> The 7-1-branch is the stable branch. The tip contains stable back-ported fixes and/or minor features that are intended for near term production use. I would not object to pulling changes from the tip of 7-1-branch for a downstream patch release of 7.7. The next version in the 7.x series will be 7.8.

I had a look at packaging the HEAD of this branch.

https://github.com/heimdal/heimdal/compare/heimdal-7.7.0...heimdal-7-1-branch

But then I noticed some things that made made me reconsider:

* The CI tests appear to be broken.
* This adds new symbols to the shared libraries, most notably `kadm5_log_goto_first` and `kadm5_log_next`.
* No changes since February.

Maybe all of this is fine. e.g. The kadm5 shared library I suspect is only used by Heimdal. But it does make me a bit nervous.

**Comment by jaltman** [comment]
> The CI tests appear to be broken.

What is broken and on what distro/version?

> This adds new symbols to the shared libraries, most notably kadm5_log_goto_first and kadm5_log_next.

These are added by bb2fe326066de3dd093768347a54ae3f6ee3a4e9 and are necessary to improve the fairness and performance of database synchronization to replica sites.

**Comment by brianmay** [comment]
> What is broken and on what distro/version?

This is entirely on the github website.

Got to the latest commit:

https://github.com/heimdal/heimdal/commit/f34394fe6974bab0a62a521efb5e64890753a440

Click the red X. You will see:

![output](https://user-images.githubusercontent.com/112729/190532336-08f56106-1525-4d39-975a-a5c9cce061c3.png)

The link takes you to https://ci.appveyor.com/project/lha/heimdal/builds/42440317

**Comment by jaltman** [comment]
appveyor is broken.   the service cannot maintain a stable environment.  It no longer can find the build dependencies and so it can no longer even get to the point of building the tree.

**Comment by jaltman** [comment]
https://github.com/heimdal/heimdal/releases
