### ISSUE TITLE
Support for 'include' and 'includedir' directives

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#89]
For distributions, it is convenient to be able to just drop files in /etc/krb5.conf.d/. MIT has support for an 'includedir' directive in krb5.conf. It'd be great if Heimdal supported this too.

I'm going to have a look at implementing this.

**Comment by quanah** [comment]
I note some improvement in current Heimdal vs Heimdal 1.6.  In Heimdal 1.6, an includedir line breaks a ton of things, like:

```
 ./verify_krb5_conf
verify_krb5_conf: krb5_init_context failed with 22
```

In current Heimdal:

```
.//verify_krb5_conf
verify_krb5_conf: krb5_config_parse_file: open /home/build/.krb5/config: No such file or directory
verify_krb5_conf: krb5_config_parse_file: /etc/krb5.conf:2: binding before section
```

The larger question is if things like
```
kdc --builtin-hdb
```
remain broken.  If so, that's problematic because the default RHEL7/CentOS7 krb5.conf has this line present.

**Comment by abartlet** [comment]
On Fri, 2017-02-10 at 16:40 -0800, Quanah Gibson-Mount wrote:
> I note some improvement in current Heimdal vs Heimdal 1.6. In Heimdal
> 1.6, an includedir line breaks a ton of things, like:
>  ./verify_krb5_conf
> verify_krb5_conf: krb5_init_context failed with 22
> In current Heimdal:
> .//verify_krb5_conf
> verify_krb5_conf: krb5_config_parse_file: open
> /home/build/.krb5/config: No such file or directory
> verify_krb5_conf: krb5_config_parse_file: /etc/krb5.conf:2: binding
> before section
> The larger question is if things like
> kdc --builtin-hdb
> remain broken. If so, that's problematic because the default
> RHEL7/CentOS7 krb5.conf has this line present.

I note that this is causing a lot of trouble in Samba with our old
snapshot of Heimdal used in the Samba AD DC

Andrew Bartlett

-- 
Andrew Bartlett                       http://samba.org/~abartlet/
Authentication Developer, Samba Team  http://samba.org
Samba Developer, Catalyst IT          http://catalyst.net.nz/services/samba

**Comment by quanah** [comment]
Looks like it is correctly ignored in the 7.0 release.

```
./kdc --builtin-hdb
builtin hdb backends: db:, db3:, keytab:, sqlite:
```

**Comment by nicowilliams** [comment]
What's the status of this?

I just whipped up a simple patch.  I could finish it if desired.

Nico
--

**Comment by jaltman** [comment]
@nico, unless @jelmer responds that there is already an existing implementation, please finish your patch.

**Comment by jelmer** [comment]
On Wed, Feb 15, 2017 at 10:42:19PM -0800, Nico Williams wrote:
> What's the status of this?
> 
> I just whipped up a simple patch.  I could finish it if desired.
FWIW I'm not actively working on this.

**Comment by nicowilliams** [comment]
I've code that works and is functionally the same as MIT's.  I don't yet have a test nor docs changes.

**Comment by nicowilliams** [comment]
https://github.com/heimdal/heimdal/compare/master...nicowilliams:include_conf?expand=1

**Comment by jelmer** [comment]
Nice!

FWIW @jaltman asked for mtime checking in https://github.com/heimdal/heimdal/issues/89#issuecomment-42687226

**Comment by nicowilliams** [comment]
I think that checking whether the configuration has changed is way, waaay out of scope.

We already *don't* do that for the default configuration today.  We could make the config system (which is roughly like the profile API in MIT) detect config changes and re-read them (MIT's profile API does this), but we copy config items to `krb5_context` all over (MIT also does this) and then updating those would be a pain (MIT is in the same boat -- `krb5_context`s don't get updated automatically because of this).

Automatically re-reading configs and _not_ automatically updating relevant fields of `krb5_context`s seems pointless, so automatically re-reading configs is a heavy-duty project.

My first stab at a high-level design is to add new versions of the config API that "register" where the values land in related external object(s) and which will update those automatically as long as the related external object(s) remain alive.  This would minimize the amount of violence visited on the callers of the config API, but it would be a fairly complex project.  An alternative would be to code up a `krb5_reinit_context()` and make sure that people touching `krb5_init_context()` know to also make corresponding updates to `krb5_reinit_context()`.

**Comment by nicowilliams** [comment]
https://github.com/heimdal/heimdal/pull/248

**Comment by nicowilliams** [comment]
> @nico, unless @jelmer responds that there is already an existing
> implementation, please finish your patch.

Viktor suggests adding infinite recursion protection, probably as a max
depth limit.  That's reasonable.  I'll have to add that, then I'll push
it.

**Comment by vdukhovni** [comment]
Closing in favour of #253
