### ISSUE TITLE
KRB-ERROR for KRB_AP_ERR_TKT_EXPIRED contains an empty sname

### ISSUE THREAD

**Issue by oldhen** [heimdal/heimdal#925]
**Describe the bug**
The ASN.1 decoding of the KRB-ERROR in response to a TGS-REQ with expired credentials (error 32 / 0x20) contains a sname field (PrincipalName) with name-type NT-UNKNOWN, and a name-string containing 0 elements.  A 0-element name-string causes an exception in Java while constructing the error-encapsulating object.

**To Reproduce**
Send TGS-REQ to 7.7.0 KDC with expired credential, decode KRB-ERROR to find empty sname.name-string

**Expected behavior**
The sname.name-string in KRB-ERROR should contain the same sname provided in the caller's TGS-REQ.req-body.sname

**Comment by lhoward** [comment]
Perhaps the change to krb5tgs.c in 2b95853df47e73074cc8ccff209065024aa32d15 fixed this as an unintended consequence.

**Comment by lhoward** [comment]
Although hmm, that patch is the TGT server not the TGS-REQ server. Further investigation required.

**Comment by lhoward** [comment]
Looking at the MIT code:

{code}
    errpkt.server = request->server;
    if (ticket && ticket->enc_part2)
        errpkt.client = ticket->enc_part2->client;
    else
        errpkt.client = NULL;
    errpkt.text.length = strlen(status);
{code}

So, it looks like the master is setting the wrong server principal. And, 7.7, no client or server principal.

**Comment by lhoward** [comment]
And for the AS:

```c
    errpkt.error = error;
    errpkt.server = request->server;
    errpkt.client = (error == KDC_ERR_WRONG_REALM) ? canon_client :
        request->client;
    errpkt.text = string2data((char *)status);
```

**Comment by nicowilliams** [comment]
This should certainly also be taken up with the Java community.  We'll have FAST for TGS in 8.1, so it'd be nice if Java used that, and then matching the `KRB-ERROR`'s sname to the request will be of no significance.

Also, I wouldn't expect anything in particular with respect to name-types in any KDC response.  Name types are only meaningful a) in KDC requests (since they might enable different canonicalization options), b) in client-side APIs (for the same reason).  Name-types do not partition the namespace of principals, and the KDC may not know the name-type of any principals in its database (I believe neither MIT's nor Heimdal's KDCs do).
