### ISSUE TITLE
kadmin fetch w/ "get-keys" privilege should not write keytab (was "get-keys" privilege is not part of "all")

### ISSUE THREAD

**Issue by ktdreyer** [heimdal/heimdal#96]
I'm using the tip of heimdal-1-6-branch, 229d8c76a29a7a292e71406485feb0b7a7451d2a

It seems that "`get-keys`" is not part of the "`all`" setting.

```
# cat /var/heimdal/kadmind.acl
kdreyer/admin all
```

And looking at my privileges with kadmin:

```
# kadmin -p kdreyer/admin privileges
kdreyer/admin@REALM.EXAMPLE.COM's Password:
change-password, list, delete, modify, add, get
```

**Comment by simmel** [comment]
What annoys me the most is that when I have `all` but not `get-keys` I can still extract principals into keytabs with `ext_keytab` BUT they are still usable in some extent except that they don't have the key/password in them.
```
50hz:~$ ktutil list
FILE:/etc/krb5.keytab:

Vno  Type                     Principal            Aliases
  1  aes256-cts-hmac-sha1-96  host/50hz.se@soy.se
  1  aes128-cts-hmac-sha1-96  host/50hz.se@soy.se
50hz:~$ kinit -k host/50hz.se
kinit: Password incorrect
```
What is the reasoning for this? Why not just disallow extraction/creation of keytabs when the user can't get the key?

I kinda agree with @lha here, but I'd say add `get-keys` to `all` and then put a deprecation warning when starting `kadmind` (or whenever `kadmind.acl` is read). But do add an `admin` role. Not sure why `everything` is better than `all` though.

Luckily, my not-so-anonymous co-worker had already ran into this issue so I didn't have to take a deep dive to solve it = )

**Comment by nicowilliams** [comment]
@simmel That's reasonable.  I'll see what I can do about that.

**Comment by nicowilliams** [comment]
Er, I believe this is fixed in that `ext_keytab` will warn about bogus keys and will not write bogus keys to keytabs.

A user who does not have the `get-keys` privilege must use `ext_keytab` with the `-r`/`-random-key` option to set a new random keyset to the principal and write that to the keytab.  (This increments the `kvno`, naturally.)

It is important that one not be able to extract keys from the database without that being noticeable.  Setting new keys on a principal is noticeable.

I consider the old behavior to be a very significant bug -- a showstopper for kadmind, really.  Of course, some of us use @elric1's krb5_admin suite and wouldn't have this problem, but that doesn't mean it's OK to ship kadmind like that.
